dist: xenial
language: go
go:
- 1.12.x
git:
  depth: 1
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
notifications:
  email: false
script:
- cd validate
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
- cd ..
- make build-all
deploy:
  provider: releases
  api_key:
    secure: VyqEgg1HXlWPoKX4+DVwNDeIvJNYVkPiGdv0quC6qdBdb+SY33wpwh4mSWyr1ZFGBTsjL8WsGR7V6Sgr/YYseqW47n9rkhUAlPghlMqP04OevHgz5Zau/urF6X6kzjoW3Df4KAmtQTSJ4Tz0TcOCO7uTqt+xnSpdIdpHnI2PeOGV64gex83MvvlpXB4NumMInY5kfHdP9FOSbKIUMAu+CXcMbbNRU24yfyd4c9B9FVEqPGxMoieA1RI3tBlMyFFh+A3Ps2LCOY4G7jum0fyxrUfJWyW8e6bh951VCzw7r9RKVKYDHLVqQ3k4OB2atwNXHrp+GgyeuR3HsrCo1TTDpMorZtVqaCcyXrkCrWEOb6T1/DvATfz0FhcVYnl2N8ZM8hne6jTQDmQ1L47CpaENGoe9fe2phXpfl6py/We9AteevqfWh11K1B2h+J04CW99uORd0yPUAp8f7v17PlZVsJeGeu85vyDCdT5t6kAKY94NEtkm4s8xAlkaRlzw+R9iGJA6AP1xD3LGOlFKdHSim1hYSODm38p3aurjY0EzsCFijPGVmJwBZZHUkUwxBai4md1DYdgt05Mpcyv31IewnpnSyEdRPVq1MwYSNGHBKx3MS0J+7yHWacVxULMHfpwazI87LRHawO3GSoiLAP+P1K/ZBLWJfK43OfsWdtj9Fww=
  file:
  - terraform-provider-validate.darwin-amd64.tar.gz
  - terraform-provider-validate.darwin-386.tar.gz
  - terraform-provider-validate.linux-amd64.tar.gz
  - terraform-provider-validate.linux-386.tar.gz
  - terraform-provider-validate.windows-amd64.tar.gz
  - terraform-provider-validate.windows-386.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  global:
    secure: wxYa4rxIpwY+fhNJ/bF227XQbHDMzCxk4ucAnvhnk2KDtBFe08t1sEvICYUdxyokMPV+/8joH8qx/NCVd/ieVXWBwVY0aSPQlW6fv4JXf9sMis8YQd32OimRQLUaPN5SvHS15zdDpKCZNe0Yz3uZCBWUI2/cbepsJWFSo+QIvXPyegkKUZgu6CYXfVZ+TdH7XEfTJu1BGb/joO/PGKoV8l3QMvrR4hlrOEXr8vXsjk+FFBnqAlSA2rp0CbAiFlDIvSHknQ0Tn3rqkwo0O7f+YtxHcP2lM6cM4BUR6VSzQfcy4ujX+yockHJC5aYzdhXxNyVfl4DgBaX07c4Yw3A+qt2FkOTGmKdkuMNQE5hoHYGdLTYwfhZui4q8tQ9l2tfzQc+sAUWv+bMzhJV+Q86diyb3/+CIO7GqKWsxWumkJuAFgw7pBTK1oN6nEpUUrMzQ+ipOHVoGjapB4ZNnAnxgW95gAxpq58ySY1dTjpV5FMJkcn+PhqdR2ubvwxp3Lne1XQo3RphQytl3fJ4UDC26LCA1EXLLV7PaGpJ833T3hhF0VKaP0X9MMD+zm1fYOEi4/3vKtKr0EmuwPaYIXgCLmlCr++vnF+NhJsAIUP0T6EurN4PjogUcy7oInk8gJHF8Y6X8XbGjlPL0s12unO/X5nK26T0oJ8ejZflognD9SfY=
