dist: xenial

language: go

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: false

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - make test
  - make build-all

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file:
    - terraform-provider-validate.darwin-amd64.tar.gz
    - terraform-provider-validate.darwin-386.tar.gz
    - terraform-provider-validate.linux-amd64.tar.gz
    - terraform-provider-validate.linux-386.tar.gz
    - terraform-provider-validate.windows-amd64.tar.gz
    - terraform-provider-validate.windows-386.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
