dist: xenial
language: go
go:
- 1.12.x
git:
  depth: 1
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
notifications:
  email: false
script:
- cd validate
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
- cd ..
- make build-all
deploy:
  provider: releases
  api_key:
    secure: X9oo1DfVVUnT//rEnNgOsA3RpPVw+9Hk/Y9Z9V4hsy1Rnf7eUhjaOZ2DjeBLmaaB9OKRxfMwz9i8kbA0fPV0C8DYsxrjWVmqSy0SYsxbbzbBLLECCBrG8szYQX+Q6tZkOyC3Y7130NJvaJLpk1ufbIbpS32OnY26P2z0kLEzPK6YKnrsWM3J0hR31jW01eUTuqil3cDfNpVrA3Di2FhXMlolvpam5iip9Jg+AXFa4/PqXO2Ikj1SZ+R8jATkTZb/YlrIxIvZmJSOUBjpz4uxnKEj9147Yx0jBRrK3wEUdlX/p+spr7lkkUOnDNXK/4GbzUy3HEXkP165aV/go/v/VwDnfui+coB3IgFQw1WuhERDD2LpvTZqCdsWnWZBb6Eh9czjXQIwMy2YloZMnIP9ccqg6sGRhdK/tcaD8LgBQRkavlYMPR5xNkvKKD3y3aVCTGI20POgIwU0Pw+Z0WqIy/oclBeS+AkMKbeH7opKgJu94Xskv+rgnk5tEAtzATtcn88C6m5huHaNtXoRNzoGrTcA8cEqSrPurOqidVIbO6NyVF68zs6dkhXA3KaS9QJ/Jc/E3wtTojQo+L3LsIR2paXA/YeqGUUvltfkGybKQwPVXkGgwzmlx5Fs9WelmxEwO/upZQz/iNM7J7fCLmHwiyG1r1EBywCwU1dOIrGorMc=
  file:
    - terraform-provider-validate.darwin-amd64.tar.gz
    - terraform-provider-validate.darwin-386.tar.gz
    - terraform-provider-validate.linux-amd64.tar.gz
    - terraform-provider-validate.linux-386.tar.gz
    - terraform-provider-validate.windows-amd64.tar.gz
    - terraform-provider-validate.windows-386.tar.gz
  skip_cleanup: true
  on:
    repo: craigmonson/terraform-provider-validate
    tags: true
env:
  global:
    secure: wxYa4rxIpwY+fhNJ/bF227XQbHDMzCxk4ucAnvhnk2KDtBFe08t1sEvICYUdxyokMPV+/8joH8qx/NCVd/ieVXWBwVY0aSPQlW6fv4JXf9sMis8YQd32OimRQLUaPN5SvHS15zdDpKCZNe0Yz3uZCBWUI2/cbepsJWFSo+QIvXPyegkKUZgu6CYXfVZ+TdH7XEfTJu1BGb/joO/PGKoV8l3QMvrR4hlrOEXr8vXsjk+FFBnqAlSA2rp0CbAiFlDIvSHknQ0Tn3rqkwo0O7f+YtxHcP2lM6cM4BUR6VSzQfcy4ujX+yockHJC5aYzdhXxNyVfl4DgBaX07c4Yw3A+qt2FkOTGmKdkuMNQE5hoHYGdLTYwfhZui4q8tQ9l2tfzQc+sAUWv+bMzhJV+Q86diyb3/+CIO7GqKWsxWumkJuAFgw7pBTK1oN6nEpUUrMzQ+ipOHVoGjapB4ZNnAnxgW95gAxpq58ySY1dTjpV5FMJkcn+PhqdR2ubvwxp3Lne1XQo3RphQytl3fJ4UDC26LCA1EXLLV7PaGpJ833T3hhF0VKaP0X9MMD+zm1fYOEi4/3vKtKr0EmuwPaYIXgCLmlCr++vnF+NhJsAIUP0T6EurN4PjogUcy7oInk8gJHF8Y6X8XbGjlPL0s12unO/X5nK26T0oJ8ejZflognD9SfY=
