dist: xenial
language: go
go:
- 1.12.x
git:
  depth: 1
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
notifications:
  email: false
script:
- cd validate && go test -v -covermode=count -coverprofile=../coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
- make build-all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - terraform-provider-validate.darwin-amd64.tar.gz
  - terraform-provider-validate.darwin-386.tar.gz
  - terraform-provider-validate.linux-amd64.tar.gz
  - terraform-provider-validate.linux-386.tar.gz
  - terraform-provider-validate.windows-amd64.tar.gz
  - terraform-provider-validate.windows-386.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  global:
  - secure: F3v8ZQ/48P8KrscQT+Uun7mZ5OK5S9GdLx+tDNwdaTP3Gyx5iA7cY8R6rDsp50dYOklRD+eja1/rSbEPaTswZp5mDQaOHcpwh0T/aHYdS2kjzMgdrNFFTVf5OD4i54vlez7ybLkMNPzkWQ6XCtK0c54oAjuneYAcD41masLnIMCUvdAoIORvqpUwNW1WsrNHxQKz297OnLV5s84/WbTlJMUAHL+RywXdDXFVFyC2bulP8p04LzKmwRmnXeSCtXNeSSPAlZ2kAg68VCY4iYLOXnvsEuKUnQkK0z8Kvw8QLVw3QoVtx+HZApEsePIkc6lUEUGEDCtClr22QMePWYt7NZGhl+hcywQZ2nwjQq42zuGC5IqFvD3Y2J0OPbTj+ezwff+QfNM+yUu20y8arys9gzAqNuWQ4MG8D8X1OjSSf13xP+pvM6CtHr7lijGt2G4X3vFTKB9APx7RzEEFnp2bdg9H768ZnKxFzE6MyX0hTwZnPSgNM8BvGCL3G4hZXj77gvlKXnyckDqKwfRpUjeR/9hgOd0tDmFwU3J+mIR7FSzIYuPV/bJRnuleE7/AVSPXjFSt9mHGi4H8O21HaL7t2sgjlfVWXC2dMfBGZois14srkLJl8r7BosS2065pxfYlO8j3MVzTxBFCw53PUqXFPaqj6xDyRjv+LFYxWT+aiN8=
  - secure: w7j9HyqTOizLSbixK7sN9TxuYTWyOewPRKMYURcYwOqKqqUr4TvV69JgKdrEmnUkeevOYU00NKCjGJYC6+/WeaVv9dTCZDktbWJgagglYMRVa+fLXjbfB+HB82ZOCTb+zafyihv9n2vr1TNP5moKcppzq+fD//BRXhFfiXnHblX+aNWj0s3BDHBnbbA0ZozFP6oaNJon8U/bb1RAPDVOxKJuQkMplR2WwVNJ6/lbjG2X+d9k0oGtjn2pAkOGmkb2WZlLZog07jyuyvMIymIoa2qaEwSMcxaYA19TdgJFUP+vcK0/aX4/mYN/DSaowMQDKJosvjUSjEnzCVjD0A3J8niYiSGG4yQB2hyX5mfEw/BsjswTPI+mY/mC1jrm5QDig/seUWLJ/IWKjGK9b2OIjD+9qVHQub6/Budet7cijjtMQpyr674HYyHEKiLhH6CylIc9ct/08rK1uh6kxD3eAsWjgNWlfslc67YZ5ZUqX9E4PbJbFjPkzJtkMygvmcedrskLHfNsutWB32wUBbBY0iogUI4gcqCacK5S/pisDM6KQyzHelN6P2DID+w2YSZId5yVLH5caG1WzsaroJe5/Ip00gTJ47xDzThhZ6E+rARvPOWyKRvzh54wdMXArk+s1jlAH96q8nLFEKjxAbLk454ERl2wNGPFqMtTWKmVfvg=
